github_fivetran:
  outputs:
    duckdb:
      type: duckdb
      threads: 4
    snowflake:
      type: snowflake
      account: "{{ prefect.blocks.snowflake-credentials.coalesce-snowflake.account }}"
      user: "{{ prefect.blocks.snowflake-credentials.coalesce-snowflake.user }}"
      password: "{{ prefect.blocks.snowflake-credentials.coalesce-snowflake.password }}"
      database: "{{ prefect.blocks.snowflake-connector.coalesce-snowflake-connector.database }}"
      schema: "{{ prefect.blocks.snowflake-connector.coalesce-snowflake-connector.schema }}"
      threads: 4
  target: snowflake